version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - notes-net

  redis:
    image: redis:latest
    networks:
      - notes-net

  api:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - notes-net
    deploy:
      replicas: 2
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - notes-net
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
    networks:
      - notes-net

networks:
  notes-net:

volumes:
  pgdata:
